import Navigation from "@/components/navigation";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";

export const metadata = {
    title: {
        template: "%s / Next Blog App",
        default: "Welcome / Next Blog App",
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AppRouterCacheProvider>
                    <header>
                        <Navigation />
                    </header>
                    <main>{children}</main>
                    <footer>Footer</footer>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
