// src/app/layout.js

import Navigation from "@/components/navigation";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Container } from "@mui/material";
import "./globals.css";

export const metadata = {
    title: {
        template: "%s / Next Blog App",
        default: "Welcome / Next Blog App",
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className="no-js"
        >
            <body className="app-body">
                <AppRouterCacheProvider>
                    <header>
                        <Navigation />
                    </header>
                    <main>
                        <Container sx={{ my: 3 }}>{children}</Container>
                    </main>
                    <footer>Footer</footer>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
